Added start.txt
nFeen/devops_git pull request #1
Opened 2024-05-19 16:36 UTC by nFeen

Added start.txt with this code:
while(true)
{
	HandleInput();
	UpdateScripts();
	DrawGraphic();
}
I dont know if this works

2024-05-19 16:47 UTC, freezefinnn commented on start.txt
> +}
Убери цикл

2024-05-19 16:47 UTC, nFeen commented on start.txt
> +}
Ок

2024-05-19 16:56 UTC, freezefinnn requested changes
Поменяй код, убери цикл

2024-05-20 16:16 UTC, freezefinnn approved these changes

2024-05-20 17:02 UTC, merged